name: Test Workflow

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install valgrind and cppcheck
        run: sudo apt install cppcheck valgrind
      - name: Compile code with g++
        run: make build
      - name: Run cppcheck code analysis
        run: make static-code-analysis
      - name: Artifact logs
        uses: actions/upload-artifact@v2
        with:
          path: ./performance_log.txt
      - name: Run memory test
        run: make memory-leak-check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile code with g++
        run: make build
      - name: Execute test and evaluate results
        run: make io-diff-tests
