name: Unit test for JSON parser

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install depedencies
        run: sudo apt install libgtest-dev && sudo apt install cmake
      - name: Run unit tests
        run: make run_unit_tests
